spring.config.import=optional:file:.env[.properties]
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${PG_ADMIN_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_test
server.port=5050
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
#logging.file.name=/mnt/c/Users/DELL/Documents/SEMICOLON/cloned/cloud_test/app.log
logging.file.name=app.log
